// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RevConnectAPI.Data.DataContext;

#nullable disable

namespace RevConnectAPI.Database.Migrations
{
    [DbContext(typeof(RevConnectContext))]
    [Migration("20220518160050_Update")]
    partial class Update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("RevConnect")
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RevConnectAPI.Data.Models.Comment", b =>
                {
                    b.Property<int>("commentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("commentID"), 1L, 1);

                    b.Property<string>("authID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("postID")
                        .HasColumnType("int");

                    b.HasKey("commentID");

                    b.HasIndex("postID");

                    b.ToTable("Comments", "RevConnect");
                });

            modelBuilder.Entity("RevConnectAPI.Data.Models.Like", b =>
                {
                    b.Property<int>("likeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("likeID"), 1L, 1);

                    b.Property<string>("authID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("commentID")
                        .HasColumnType("int");

                    b.Property<int?>("postID")
                        .HasColumnType("int");

                    b.HasKey("likeID");

                    b.HasIndex("commentID");

                    b.HasIndex("postID");

                    b.ToTable("Likes", "RevConnect");
                });

            modelBuilder.Entity("RevConnectAPI.Data.Models.Post", b =>
                {
                    b.Property<int>("postID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("postID"), 1L, 1);

                    b.Property<string>("authID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("postID");

                    b.ToTable("Posts", "RevConnect");
                });

            modelBuilder.Entity("RevConnectAPI.Data.Models.User", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userID"), 1L, 1);

                    b.Property<string>("aboutMe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("authID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("github")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("linkedin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("twitter")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userID");

                    b.ToTable("Users", "RevConnect");
                });

            modelBuilder.Entity("RevConnectAPI.Data.Models.Comment", b =>
                {
                    b.HasOne("RevConnectAPI.Data.Models.Post", null)
                        .WithMany("postComments")
                        .HasForeignKey("postID");
                });

            modelBuilder.Entity("RevConnectAPI.Data.Models.Like", b =>
                {
                    b.HasOne("RevConnectAPI.Data.Models.Comment", null)
                        .WithMany("commentLikes")
                        .HasForeignKey("commentID");

                    b.HasOne("RevConnectAPI.Data.Models.Post", null)
                        .WithMany("postLikes")
                        .HasForeignKey("postID");
                });

            modelBuilder.Entity("RevConnectAPI.Data.Models.Comment", b =>
                {
                    b.Navigation("commentLikes");
                });

            modelBuilder.Entity("RevConnectAPI.Data.Models.Post", b =>
                {
                    b.Navigation("postComments");

                    b.Navigation("postLikes");
                });
#pragma warning restore 612, 618
        }
    }
}
