         
  # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - RevConnectApp

on:
  push:
    branches: [ main ]
    paths:
      - 'RevConnectApp/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          
      - name: move Directory
        run: |
         ls .
         cd .\RevConnectApp
         ls .

      - name: npm install, build, and test
        run: |
          ls .
          cd .\RevConnectApp
          ls .
          npm install
          npm run build --if-present          

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'RevConnectApp'
          slot-name: 'production'
          publish-profile: ${{ secrets.DAN_AZURE_APP_PROFILE }}
          package: ./RevConnectApp/dist
